### ISSUE TITLE
Issue with BetterWarden

### ISSUE THREAD

**Issue by stevenhoro** [condolent/Better-Warden#7]
Plugin Version:  Latest Official
Sourcemod/Metamod Version:  Latest Official
Error Logs:  No Errors
Plugin Config:  Default

The plugin itself is working fine, but I noticed that players are unable to type anything in regular deadchat.  When you type a message, it will not appear to anyone and won't even appear to yourself.  However, team deadchat still works and any other chat works as well.  Is this the result of the plugin itself or could it be conflicting with chat-based plugins?

**Comment by jonteohr** [comment]
By _latest official_ version of the plugin, do you mean 0.6.3.2? There's been alot of people thinking 0.6.3.4 is the latest, but that is just a development version and filled with bugs and stuff.

**Comment by jonteohr** [comment]
Nevermind, it seemed to be a simple error in the code. Fixed in [fe19cbb](https://github.com/condolent/Better-Warden/commit/fe19cbb)

**Comment by jonteohr** [comment]
And also pushed to master in #8
